## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here
import numpy as np

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [17]:
# okay numpy is great but... how would you inverse a matrix by hand?

def inverse_matrix(A,B):
    
    A = np.array([[0.6, -15, 2, 5, 98]])
    B = np.array([[2,9,13,1,0],[2,-14,-0.5,9,0],[-4,0,44,4,5]])
    C = A*B
    C1 = B*A
    return C, C[1][2], C1
inverse_matrix(A,B)

    

(array([[   1.2, -135. ,   26. ,    5. ,    0. ],
        [   1.2,  210. ,   -1. ,   45. ,    0. ],
        [  -2.4,   -0. ,   88. ,   20. ,  490. ]]),
 -1.0,
 array([[   1.2, -135. ,   26. ,    5. ,    0. ],
        [   1.2,  210. ,   -1. ,   45. ,    0. ],
        [  -2.4,   -0. ,   88. ,   20. ,  490. ]]))

![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [19]:
# Just answer using code --> easy stuff!
A = np.array([[3,-1.3,7],[0.6,4,0],[4,0,-8],[-3,8.6,0.006]])
B = np.array([[3,2,-9],[-5.76,-2,0],[45,1.3,0],[0,9,0]])
C = np.array([[0,0,-7.7],[1009,5,0],[-66.7849,4,0],[90,-0.07,0]])
D = A+B-C
print(D)
print(D[1][2])
D[2][0]

# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

[[ 6.000000e+00  7.000000e-01  5.700000e+00]
 [-1.014160e+03 -3.000000e+00  0.000000e+00]
 [ 1.157849e+02 -2.700000e+00 -8.000000e+00]
 [-9.300000e+01  1.767000e+01  6.000000e-03]]
0.0


115.7849

![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [26]:
A = np.array([[0.6, -15, 2, 5, 98]])
B = np.array([[2,9,13,1,0],[2,-14,-0.5,9,0],[-4,0,44,4,5]])
C = A*B
print(C)
print(C.shape)
C[0][2]


[[   1.2 -135.    26.     5.     0. ]
 [   1.2  210.    -1.    45.     0. ]
 [  -2.4   -0.    88.    20.   490. ]]
(3, 5)


26.0