# Vectors and Matrices
Time to work! Do it with numpy first and then if you have time, manually by hand :)

## Vectors

Lists can be used to represent mathematical vectors. In this exercise and several that follow you will write functions to perform standard operations on vectors. Create a file named vectors.py or use the Jupyter notebook provided

Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.

**Note that the text in """ """ is provided for you to accurately verify that your function works :)**

In [2]:
import numpy as np

In [3]:
def add_vectors(u, v):
    """
      >>> add_vectors([1, 0], [1, 1])
      [2, 1]
  
      >>> add_vectors([1, 2], [1, 4])
      [2, 6]
      >>> add_vectors([1, 2, 1], [1, 4, 3])
      [2, 6, 4]
      >>> add_vectors([11, 0, -4, 5], [2, -4, 17, 0])
      [13, -4, 13, 5]
      >>> a = [1, 2, 3]
      >>> b = [1, 1, 1]
      >>> add_vectors(a, b)
      [2, 3, 4]
      >>> a
      [1, 2, 3]
      >>> b
      [1, 1, 1]
    """
    u = np.array([1, 0])
    v = np.array([1, 1])
    u1 = np.array([1, 2])
    v1 = np.array([1, 4])
    u2 = np.array([1, 2, 1])
    v2 = np.array([1, 4, 3])
    u3 = np.array([11, 0, -4, 5])
    v3 = np.array([2, -4, 17, 0])
    a = np.array([1, 2, 3])
    b = np.array([1, 1, 1])
    return u+v, u1+v1, u2+v2, u3+v3, a+b
    
add_vectors([1, 0], [1, 1])

(array([2, 1]),
 array([2, 6]),
 array([2, 6, 4]),
 array([13, -4, 13,  5]),
 array([2, 3, 4]))

Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the [scalar multiple](https://en.wikipedia.org/wiki/Scalar_multiplication) of v by s.

In [5]:
def scalar_mult(a,b):
    """
      >>> scalar_mult(5, [1, 2])
      [5, 10]
      >>> scalar_mult(3, [1, 0, -1])
      [3, 0, -3]
      >>> scalar_mult(7, [3, 0, 5, 11, 2])
      [21, 0, 35, 77, 14]
      >>> a = [1, 2, 3]
      >>> scalar_mult(4, a)
      [4, 8, 12]
      >>> a
      [1, 2, 3]
    """
    a = np.array([5])
    b =np.array([1, 2])
    a1 = np.array([3])
    b1 =np.array([1, 0, -1])
    a2 = np.array([7])
    b2 =np.array([3, 0, 5, 11, 2])
    return a*b, a1*b1, a2*b2
scalar_mult(5, [1, 2])    

(array([ 5, 10]), array([ 3,  0, -3]), array([21,  0, 35, 77, 14]))

Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the [dot_product](https://en.wikipedia.org/wiki/Dot_product).

In [6]:
def dot_product(u, v):
    """
      >>> dot_product([1, 1], [1, 1])
      2
      >>> dot_product([1, 2], [1, 4])
      9
      >>> dot_product([1, 2, 1], [1, 4, 3])
      12
      >>> dot_product([2, 0, -1, 1], [1, 5, 2, 0])
      0
    """
    u1 = np.array([1, 2])
    v1 = np.array([1, 4])
    u2 = np.array([1, 2, 1])
    v2 = np.array([1, 4, 3])
    return np.dot(u,v), np.dot(u1,v1), np.dot(u2,v2)

dot_product([1, 1], [1, 1])   


(2, 9, 12)

## Matrices

Create a new module named matrices.py or *use the Jupyter notebook provided* and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [14]:
def copy_matrix(matrix):
    """
      >>> copy_matrix([[1, 2], [3, 4]])
      [[1, 2], [3, 4]]
      >>> copy_matrix([[1, 2, 3], [4, 5, 6]])
      [[1, 2, 3], [4, 5, 6]]
      >>> copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])
      [[1, 2], [3, 4], [5, 6], [7, 8]]
      >>> m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> copyofm = copy_matrix(m)
      >>> copyofm
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> for row_num, row in enumerate(copyofm):
      ...     for col_num, col_val in enumerate(row):
      ...         copyofm[row_num][col_num] = 42
      ...
      >>> copyofm
      [[42, 42, 42], [42, 42, 42], [42, 42, 42]]
      >>> m
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
    """
    copyofm = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])

    
  
    for row_num, row in enumerate(copyofm):
      for col_num, col_val in enumerate(row):
        copyofm[row_num][col_num] = 42
    return copyofm      


copy_matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])    

array([[42, 42, 42],
       [42, 42, 42],
       [42, 42, 42]])

In [25]:
def add_row(matrix):
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_row(m)
      [[0, 0], [0, 0], [0, 0]]
      >>> n = [[3, 2, 5], [1, 4, 7]]
      >>> add_row(n)
      [[3, 2, 5], [1, 4, 7], [0, 0, 0]]
      >>> n
      [[3, 2, 5], [1, 4, 7]]
    """
    m = np.array([[0, 0], [0, 0]])
    return 

add_row([[0, 0], [0, 0]])

TypeError: _apply_along_axis_dispatcher() missing 2 required positional arguments: 'axis' and 'arr'

In [ ]:
def add_column(matrix):
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_column(m)
      [[0, 0, 0], [0, 0, 0]]
      >>> n = [[3, 2], [5, 1], [4, 7]]
      >>> add_column(n)
      [[3, 2, 0], [5, 1, 0], [4, 7, 0]]
      >>> n
      [[3, 2], [5, 1], [4, 7]]
    """
    pass

Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [34]:
def add_matrices(m1, m2):
    """
      >>> a = [[1, 2], [3, 4]]
      >>> b = [[2, 2], [2, 2]]
      >>> add_matrices(a, b)
      [[3, 4], [5, 6]]
      >>> c = [[8, 2], [3, 4], [5, 7]]
      >>> d = [[3, 2], [9, 2], [10, 12]]
      >>> add_matrices(c, d)
      [[11, 4], [12, 6], [15, 19]]
      >>> c
      [[8, 2], [3, 4], [5, 7]]
      >>> d
      [[3, 2], [9, 2], [10, 12]]
   """
    a = np.array([[1, 2], [3, 4]])
    b = np.array([[2, 2], [2, 2]])
    return a+b
add_matrices([[1, 2], [3, 4]],[[2, 2], [2, 2]])    

array([[3, 4],
       [5, 6]])

Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [37]:
def scalar_mult(s, m):
    """
      >>> a = [[1, 2], [3, 4]]
      >>> scalar_mult(3, a)
      [[3, 6], [9, 12]]
      >>> b = [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
      >>> scalar_mult(10, b)
      [[30, 50, 70], [10, 10, 10], [0, 20, 0], [20, 20, 30]]
      >>> b
      [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
    """
    a = [[1, 2], [3, 4]]
    m = np.array(a)
    return s*m

scalar_mult(3,[[1, 2], [3, 4]])    

array([[ 3,  6],
       [ 9, 12]])

Write functions row_times_column and matrix_mult:

In [10]:
def row_times_column(m1, row, m2, column):
    """
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
      19
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)
      22
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
      43
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)
      50
    """
    a = np.array([[1, 2], [3, 4]])
    b = np.array([[5, 6], [7, 8]])
    return a*b
    

In [46]:

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [13]:
def matrix_mult(m1, m2):
    """
      >>> matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])
      [[19, 22], [43, 50]]
      >>> matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
      [[31, 19], [85, 55]]
      >>> matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]])
      [[39, 54, 69], [13, 23, 33], [14, 19, 24]]
    """
    

Write a function transpose that takes a matrix as an argument and returns is transpose:

In [39]:
def transpose(m):
    """
     >>> m = [[3, 4, 6]]
     >>> transpose(m)
     [[3], [4], [6]]
     >>> m
     [3, 4, 6]
     >>> m = [[3, 4, 6], [1, 5, 9]]
     >>> transpose(m)
     [[3, 1], [4, 5], [6, 9]]
   """
    m = np.array([[3, 4, 6]])
    return m.T
transpose([[3, 4, 6]])    

array([[3],
       [4],
       [6]])