## Linear Algebra Quiz #1

![title](./img/1_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here
import numpy as np

![title](./img/1_1.png)

In [15]:
# type a function that given a 3_dimensional vector it is able to calculate its magnitude

def magnitude_3(a,b,c):
    x = np.array([a,b,c])
    return np.linalg.norm(x)
magnitude_3(a=1, b=2, c=3)    

# type a function that given a n_dimensional vector it is able to calculate its magnitude
# if you want to try this from python (not jupyter notebook) https://docs.python.org/3/library/argparse.html would be a good addition
# if you are doing this from a jupyter notebook only, you can try to prompt the user for an input  

# def magnitude_complete():
    

3.7416573867739413

uncomment the following line when you are ready to test

In [12]:
assert magnitude_complete(1) == 1.0
assert magnitude_complete(1,2) >= 2.236
assert magnitude_complete(1,2,3) >= 3.741
assert magnitude_complete(1,2,3,4,5) >= 5.477
assert magnitude_complete(1,2,3,4,5) >= 7.416

TypeError: 'numpy.float64' object is not callable

![title](./img/1_2.png)

In [35]:
def magnitude_vectors(a, b):
    #checks that size is equal
    a = np.array([[5],[1]])
    b = np.array([[-4],[-1]])
    if True:
        a.size == b.size
    
    #returns the magnitude
    return np.linalg.norm(a), np.linalg.norm(b), np.linalg.norm(a+(-b))
magnitude_vectors(a,b)

(5.0990195135927845, 4.123105625617661, 9.219544457292887)

![title](./img/1_3.png)

In [42]:
def direction_vectors(a, b):
    #checks that size is equal
    a = np.array([[5],[1]])
    b = np.array([[-4],[-1]])
    if True:
        a.size == b.size
    #returns the angle. Hint: use the arctan
    return np.arctan(a), np.arctan(b),np.linalg.norm(a+(-b))
direction_vectors(a,b)    
# or if you want to do it all in one batch:
# def magdir_vectors(a, b):
    #checks that size is equal
    
    #returns the magnitude and direction 
    # as alternative, print them in a nicely printed format like:
    #"The magnitude of a + b is X and the direction is Y"

(array([[1.37340077],
        [0.78539816]]),
 array([[-1.32581766],
        [-0.78539816]]),
 9.219544457292887)

![title](./img/1_4.png)
- What is the magnitude of αx⃗? 
- If α>0, will the direction of the resulting vector change?
- If α<0, will the direction of the resulting vector change?
- If −1<α<1, will ∥αx⃗∥  increase, decrease or stay the same?

In [ ]:
# def alpha_magnitude(alpha, b):
    
    #returns the resulting magnitude,
    # as alternative, just print it



For the above exercise, write down in markdown or in a comment if the direction has changed and what has happened to the vector.

In [49]:
a =2
b=4
x = np.array([[a],[b]])
c = 2
y = x*c
print(np.linalg.norm(y))
np.arctan(y)




8.94427190999916


array([[1.32581766],
       [1.44644133]])

In [48]:
a =2
b=4
x = np.array([[a],[b]])
c = -3
y = x*c
print(np.linalg.norm(y))
(np.arctan(y))

13.416407864998739


array([[-1.40564765],
       [-1.48765509]])

In [51]:
a =2
b=4
x = np.array([[a],[b]])
c = 1/2
y = x*c
print(np.linalg.norm(y))


2.23606797749979
